### ISSUE TITLE
stripeCustomerId errors on return due to casing mismatch

### ISSUE THREAD

**Issue by ndimatteo** [clerkinc/use-stripe-subscription-demo#1]
The `findOrCreateCustomerId()` function returns the Clerk user's Stripe Customer ID from the `publicMetadata` object, however it seems that Clerk converts **camelCase** to **snake_case**, so this becomes undefined, causing a typescript error due to the `string` requirement.

Changing [this line](https://github.com/clerkinc/use-stripe-subscription-demo/blob/main/utils/findOrCreateCustomerId.ts#L33) to return this instead works:
```js
return user.publicMetadata.stripe_customer_id as string;
```

**Comment by perkinsjr** [comment]
This was fixed with latest updates
